### ISSUE TITLE
Integrate the question/prompts in some way (we could talk about how on monday 7/19)

### ISSUE THREAD

**Issue by luivader** [luivader/meet-a-dime#67]
When users sign up, they don't initally have answers to the 12 question prompts. They can go into profile page and change them through the link there. Once they edit them for the first time, on their user document it the 'intializedProfile' flag gets set from 0 to 1. We should come up with a way to use that during chat

**Comment by natalieR-S** [comment]
Idea: Add a drop up menu on the right most part of text field for question bank
